### PR TITLE
Add support for screenshots in GUI

### LINKED ISSUE #105: Plugin has issues when saving base images via the GUI `cypress open` or `open-ct`
Hi there!

It seems that when `compareSnapshot` is used in a component test - it places the files under `cypress/snapshots/actual/All Specs` 

And it seems that running `npx cypress open-ct --env type=base` crashes with

```
ENOENT: no such file or directory, copyfile 
```
It is trying to copy **FROM**
`'./cypress/snapshots/base/components/MyComponent/__tests__/MyTest.visual.spec.tsx/<key>-1637840875914.png'`
**TO**
`'./cypress/snapshots/base/components/MyComponent/__tests__/MyTest.visual.spec.tsx/<key>-base.png'`

But the issue is that in a component test it seems to actually put the screenshots into `./cypress/snapshots/<type>/All Specs` instead of the full component path.

## The problem
I have been digging into the plugin source and i cannot figure out where the `All Specs` comes from. 

If @mjhea0 you know more - please let me know and I'll put up a fix!

Thanks

### PR DESCRIPTION
**Pull request by dan-cooke**
* There is a bug open in Cypress that causes the default screenshot
  location when running via the GUI to be `All Specs/` which messes up
  this plugin.

* Quick hacky fix to fallback to `All Specs/` if the original directory
  cannot be found.

Resolves #105

### CODE REVIEW

**Comment by mjhea0** [comment]
Thanks for the PR, @dan-cooke!

Looks like quite a few tests are breaking. Can you please address them? Also, can you add some tests to cover your code changes?

**Comment by gearsdigital** [comment]
@dan-cooke I'm also interested in getting this merged. Can I help you out here?

**Comment by dan-cooke** [comment]
@mjhea0 @gearsdigital apologies this one went under my radar.

Been a while. If you fancy fixing the tests we can get this merged. 

Not sure when I can get around to it at the moment

**Comment by gearsdigital** [comment]
It looks like your change works fine but it fails because a lint issue.

**Comment by dan-cooke** [comment]
@gearsdigital oh simple. I'll fix lint now

**Comment by gearsdigital** [comment]
That would be totally awesome!

**Comment by dan-cooke** [comment]
@gearsdigital  updated

**Comment by gearsdigital** [comment]
Let's see if I was right 🙈 Otherwise I'll jump in and try to fix the issues.

**Comment by gearsdigital** [comment]
@mjhea0 Would you mind to approve the Workflow? (Didn't know that is necessary)

**Comment by dan-cooke** [comment]
Looks like its prettier checks failing it now @gearsdigital  

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress-visual-regression@1.7.0 prettier:check: `prettier --check --trailing-comma es5 --single-quote --arrow-parens always "src/**/*.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress-visual-regression@1.7.0 prettier:check script.
```

**Comment by gearsdigital** [comment]
It looks like you've accidentally reformated the code 🫣👀 There is a [task](https://github.com/mjhea0/cypress-visual-regression/blob/master/package.json#L23) which seems to fix such issues `npm run prettier:fix`

**Comment by Zaista** [comment]
Too old, closing

**Pull request closed without merging**
