### PR TITLE
adds perPixelMismatchTolerance option

### PR DESCRIPTION
**Pull request by lgenzelis**
This addresses #114

### CODE REVIEW

**Comment by mjhea0** [comment]
Thanks for the PR, @lgenzelis. Looks like there's some failing tests...

**Comment by lgenzelis** [comment]
Thanks @mjhea0 ! Please, can you show me how to run the tests locally? I haven't been able to do so. I did a fresh clone of the repo, just in case. Then
```
npm install
npm run ci
```
I get the error `sh: cypress: command not found`. So, it seems I need to have cypress installed globally. I install it and run `npm run ci` again. And now I get the error:
```
Could not find a Cypress configuration file in this folder: /Users/lucas.genzelis/Pager/Projects/Others/cypress-visual-regression
```
😞

**Comment by lgenzelis** [comment]
Hey @mjhea0 ! Sorry to bug you, I just wanted to make sure you got my last message. 🙂

**Comment by mjhea0** [comment]
Apologies, @lgenzelis. I missed your previous message. 

You need to have Docker installed, to run them, you need to run the `test.sh` file. 

On my Mac machine, I run:

```sh
sh test.sh
```

**Pull request closed without merging**
