### PR TITLE
Migrating to TypeScript: Improving the Quality and Stability of Codebase

### PR DESCRIPTION
**Pull request by mrhyde**
I have taken the liberty of starting the process of migrating this plugin to Typescript. It will improve the quality and stability of the codebase and make it more maintainable and easier to work with. I am confident that this move will lead to better outcomes for the project and its users.

TODO:
- [x] Replace `babel` with `typescript` compiler
- [x] Setup `tsconfig` that will produce the same output as `babel`
- [x] Update eslint rules to work with typescript
- [x] Update jest configuration to work with ts
- [x] Migrate code
- [x] Replace `airbnb` ruleset for eslint with `standard`
- [x] Replace `console.log` calls with `debug`
- [ ] Migrate tests
- [ ] (optional) enable [strictest ](https://github.com/tsconfig/bases#strictest-tsconfigjson) set of rules for typescript compiler

### CODE REVIEW

**Comment by mrhyde** [comment]
Just wanted to give an update about the codebase conversion. The good news is that all the source files are now converted and I have confirmed that Jest tests are passing as expected.

However, I wanted to let you know that the conversion process was done in a rather rudimentary way, so my next step will be to perform refactoring to improve the quality of the codebase. Additionally, I still need to update the ESLint config to make it work with Typescript, which is currently failing.

**Comment by mrhyde** [comment]
Just wanted to give you a heads up - I updated our eslint config to work with TypeScript. It now includes some new rules related to imports and promises to ensure we're following best practices.

Also, the Airbnb config that was used is now set up for TypeScript support, so it's all good to go.

Let me know if you have any questions or concerns!

P.S. Just a quick note that we had to use `override` for `tsconfig-paths` package in our `package.json` because of one single guy being too stubborn to merge a pull request, which caused some compatibility issues. see https://github.com/import-js/eslint-plugin-import/pull/2447

**Comment by area73** [comment]
hey, @mrhyde 
I upload my [PR](https://github.com/cypress-visual-regression/cypress-visual-regression/pull/184), have a look at it.
I think it addresses your missing checks.

I guess we can work in either branch. 

Let @Zaista to pop in and decide how to proceed and what path to follow. I 'll be more than happy to collaborate in any of the branches

**Comment by mrhyde** [comment]
Hi @area73!
I just wanted to say thanks for sharing your code! I've gone through the commits and have some comments/suggestions regarding the current state. Here are my thoughts:

- In order to enable the strictest set of rules, we'll need to refactor the codebase to match them first. Once that's done, we can easily extend from `@tsconfig/strictest` as per TypeScript v5 configuration.
- I also think switching to `eslint-config-standard-with-typescript` would be better than using Airbnb config, as it covers more cases and best practices.
- Switching from console.log to debug is also a good idea, so I'll go ahead and incorporate those changes in this branch.

**Comment by mrhyde** [comment]
@area73 I think it's a good idea to stick with the standard rule of using single quotes instead of prettier default double quotes. It helps maintain consistency.

**Comment by mrhyde** [comment]
@area73 
I cherry-picked most of the commits and changes from your branch, and I'll clean it up to get it to a working state. However, I have a question about your last commit that introduced the `cpy` package. Can you describe the issue that you were facing, and why you felt the need to introduce this package?

Also, I've added you as a collaborator to my fork, so feel free to commit any changes there too.

**Comment by area73** [comment]
hey [mrhyde](https://github.com/mrhyde) , nice thanks for the invite.
Now I'm on vacation but I will catch up with you next week.
The use of cpy was because since I was updating the TS files I needed to copy other files not generated with TSC (basically the other js files that were not yet converted to TS), to dist folder when running sh script. The problem is that sh does not has `cp` command to copy files and that was the reason to use it , but you can safely omit it  👍

**Comment by mrhyde** [comment]
- `getValueOrDefault` was actually making code less readable. Dropped it in favor of simply using nullish coalescing operator when needed
- `deserializeError` was offloaded to much mature and developed implementation

**Comment by Radik24** [comment]
Hi, any update on this? Thanks

**Pull request closed without merging**
